# Generated by Django 6.0.1 on 2026-01-12 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', verbose_name='Photo de profil')),
                ('description', models.TextField(blank=True, verbose_name='Description/Bio')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('lien_cv', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Lien CV')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('detail', models.TextField(verbose_name='Détails')),
                ('type_service', models.CharField(choices=[('DEV_WEB', 'Développement Web'), ('DEV_MOBILE', 'Développement Mobile'), ('DEV_BACKEND', 'Développement Backend'), ('DEV_FRONTEND', 'Développement Frontend'), ('API', "Création d'API"), ('CONSULTING', 'Consulting'), ('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance')], max_length=20, verbose_name='Type de service')),
                ('outils', models.CharField(blank=True, help_text='Séparer par des virgules', max_length=500, verbose_name='Outils/Technologies utilisés')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Service disponible')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/images/', verbose_name='Image du projet')),
                ('lien', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Lien du projet (GitHub, démo, etc.)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Projet actif')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='api.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actuelle', models.BooleanField(default=True, verbose_name='Localisation actuelle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='api.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'ordering': ['-est_actuelle', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle/Poste')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI - Contrat à Durée Indéterminée'), ('CDD', 'CDD - Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (vide si en cours)')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name="Email de l'expéditeur")),
                ('objet', models.CharField(max_length=300, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_recus', to='api.utilisateur', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(choices=[('GITHUB', 'GitHub'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter/X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('PORTFOLIO', 'Site Portfolio'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Nom de la plateforme')),
                ('lien', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Lien du profil')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Lien actif')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseaux_sociaux', to='api.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Réseaux Sociaux',
                'ordering': ['nom_plateforme'],
                'unique_together': {('utilisateur', 'nom_plateforme')},
            },
        ),
    ]
