# Generated by Django 6.0.1 on 2026-03-06 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fichier_cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV (fichier PDF)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI - Contrat à Durée Indéterminée'), ('CDD', 'CDD - Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('FORMATION', 'Formation / Études')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='lien_cv',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Lien CV (URL externe)'),
        ),
    ]
