# Generated by Django 6.0.1 on 2026-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilisateur_fichier_cv_alter_experience_type_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='niveau',
            field=models.PositiveIntegerField(default=80, help_text='Entre 0 et 100', verbose_name='Niveau de maîtrise (%)'),
        ),
    ]
